// HydroSense - Comprehensive Hydroponic Plant & Disease Database

export const PLANTS = {
  lettuce: {
    id: 'lettuce',
    name: 'Marul',
    nameEn: 'Lettuce',
    emoji: '🥬',
    category: 'leafy',
    growthDays: { min: 30, max: 45 },
    optimalPH: { min: 5.5, max: 6.5 },
    optimalEC: { min: 0.8, max: 1.6 },
    optimalTemp: { min: 15, max: 22 },
    lightHours: 16,
    description: 'Hidroponik sistemlerde en popüler yaprak sebzelerinden biri. NFT ve DWC sistemlerinde mükemmel sonuç verir.',
    tips: ['Sıcaklık 24°C üzerinde çiçeklenmeye gidebilir', 'Kök çürüklüğüne karşı dikkatli olun', 'Besin solüsyonunu haftada 2 kez kontrol edin'],
  },
  basil: {
    id: 'basil',
    name: 'Fesleğen',
    nameEn: 'Basil',
    emoji: '🌿',
    category: 'herb',
    growthDays: { min: 25, max: 35 },
    optimalPH: { min: 5.5, max: 6.5 },
    optimalEC: { min: 1.0, max: 1.6 },
    optimalTemp: { min: 20, max: 28 },
    lightHours: 14,
    description: 'Hızlı büyüyen aromatik bir bitki. Aeroponik ve NFT sistemlerinde harika performans gösterir.',
    tips: ['Düzenli budama verimi artırır', '18°C altı sıcaklıklarda büyüme durur', 'Downy mildew\'e karşı dikkatli olun'],
  },
  cucumber: {
    id: 'cucumber',
    name: 'Salatalık',
    nameEn: 'Cucumber',
    emoji: '🥒',
    category: 'fruiting',
    growthDays: { min: 50, max: 70 },
    optimalPH: { min: 5.5, max: 6.0 },
    optimalEC: { min: 1.7, max: 2.5 },
    optimalTemp: { min: 22, max: 28 },
    lightHours: 18,
    description: 'Yüksek verimli bir meyve sebze. Büyük hacimli besin çözeltisi tankı gerektirir.',
    tips: ['Dikey destek sistemi şart', 'Yüksek EC değeri gerektirir', 'Beyaz sinek sorununa dikkat edin'],
  },
  tomato: {
    id: 'tomato',
    name: 'Domates',
    nameEn: 'Tomato',
    emoji: '🍅',
    category: 'fruiting',
    growthDays: { min: 60, max: 80 },
    optimalPH: { min: 5.5, max: 6.5 },
    optimalEC: { min: 2.0, max: 3.5 },
    optimalTemp: { min: 20, max: 26 },
    lightHours: 18,
    description: 'Hidroponikteki en popüler meyve sebzelerinden. Yüksek besin ihtiyacı vardır.',
    tips: ['Tozlaştırma için hafifçe sallayın', 'Kalsiyum eksikliği çiçek ucunu çürütür', 'Çok yüksek EC meyveyi küçültür'],
  },
  strawberry: {
    id: 'strawberry',
    name: 'Çilek',
    nameEn: 'Strawberry',
    emoji: '🍓',
    category: 'fruiting',
    growthDays: { min: 60, max: 90 },
    optimalPH: { min: 5.5, max: 6.5 },
    optimalEC: { min: 1.0, max: 1.8 },
    optimalTemp: { min: 15, max: 22 },
    lightHours: 12,
    description: 'NFT kanallarında ve dikey sistemlerde harika büyüyen bir meyve.',
    tips: ['Uyku dönemi için soğuk uygulaması gerekir', 'Gri küf (Botrytis) en büyük tehdit', 'pH\'ı hassas tutun'],
  },
  saffron: {
    id: 'saffron',
    name: 'Safran',
    nameEn: 'Saffron',
    emoji: '🌸',
    category: 'specialty',
    growthDays: { min: 90, max: 120 },
    optimalPH: { min: 6.0, max: 7.0 },
    optimalEC: { min: 0.5, max: 1.2 },
    optimalTemp: { min: 10, max: 18 },
    lightHours: 12,
    description: 'Dünyanın en değerli baharatı. Soğanlı bitkiler için özel hidroponik sistemler gerektirir.',
    tips: ['Soğuk süre zorunlu', 'Aşırı neme karşı hassas', 'Çiçeklenme döneminde su azaltın'],
  },
  spinach: {
    id: 'spinach',
    name: 'Ispanak',
    nameEn: 'Spinach',
    emoji: '🥗',
    category: 'leafy',
    growthDays: { min: 25, max: 40 },
    optimalPH: { min: 6.0, max: 7.0 },
    optimalEC: { min: 1.8, max: 2.3 },
    optimalTemp: { min: 10, max: 20 },
    lightHours: 12,
    description: 'Soğuk iklimi seven hızlı büyüyen bir yaprak sebze.',
    tips: ['Uzun gün uzunluklarında çiçeklenir', 'Demir eksikliğine dikkat', 'Serin ortamda en iyi kaliteyi verir'],
  },
  pepper: {
    id: 'pepper',
    name: 'Biber',
    nameEn: 'Bell Pepper',
    emoji: '🫑',
    category: 'fruiting',
    growthDays: { min: 70, max: 90 },
    optimalPH: { min: 5.5, max: 6.5 },
    optimalEC: { min: 2.0, max: 3.0 },
    optimalTemp: { min: 22, max: 30 },
    lightHours: 16,
    description: 'Yüksek verimli meyve sebze. Sıcak ortamı ve yüksek EC değerini sever.',
    tips: ['Yüksek sıcaklık sever', 'Kalsiyum magnezyum dengesi önemli', 'Düzenli budama şart'],
  },
};

export const DISEASES = {
  // ROOT DISEASES
  root_rot: {
    id: 'root_rot',
    name: 'Kök Çürüklüğü',
    nameEn: 'Root Rot',
    pathogen: 'Pythium spp.',
    severity: 'critical',
    affectedPlants: ['lettuce', 'basil', 'tomato', 'cucumber', 'strawberry', 'spinach', 'pepper'],
    visualSymptoms: {
      roots: 'Kahverengi, siyah, sümüksü kökler. Sağlıklı kökler beyaz veya krem rengi olmalı.',
      leaves: 'Sararma, solma ve büyüme durması. Alt yapraklar önce etkilenir.',
      stem: 'Kök boğazında koyu kahverengi renk değişimi ve yumuşama.',
    },
    causes: [
      'Oksijensiz su ortamı',
      'Aşırı yüksek su sıcaklığı (>24°C)',
      'Yetersiz hava pompası kapasitesi',
      'Kontamine besin solüsyonu',
      'Kirli rezervuar',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Acil Müdahale',
        steps: [
          'Etkilenen bitkileri hemen izole edin',
          'Çürümüş kökleri steril makasla kesin',
          'Kökleri %3\'lük hidrojen peroksit (H₂O₂) ile 30 saniye bekletin',
          'Temiz suyla durulayın',
          'Trichoderma harzianum solüsyonu uygulayın',
        ],
      },
      {
        type: 'systemic',
        title: 'Sistem Temizliği',
        steps: [
          'Tüm besin solüsyonunu boşaltın',
          '%10\'luk sodyum hipoklorit ile tankı sterilize edin',
          '3-4 kez temiz suyla durulayın',
          'Su sıcaklığını 18-22°C arasına düşürün',
          'Hava pompası kapasitesini artırın',
          'Bakır iyonu solüsyonu ekleyin (0.1 ppm)',
        ],
      },
      {
        type: 'prevention',
        title: 'Önleyici Tedbirler',
        steps: [
          'Su sıcaklığını her gün kontrol edin',
          'Rezervuarı haftada bir temizleyin',
          'UV sterilizatör kullanın',
          'Benefisiyel bakteriler (Bacillus subtilis) ekleyin',
          'Besin solüsyonunu 2 haftada bir tamamen değiştirin',
        ],
      },
    ],
    prevention: ['Su sıcaklığını 20°C altında tutun', 'Güçlü havalandırma sağlayın', 'UV sterilizatör kullanın'],
    recoveryChance: 60,
    recoveryTime: '1-3 hafta',
  },

  powdery_mildew: {
    id: 'powdery_mildew',
    name: 'Külleme (Unlu Küf)',
    nameEn: 'Powdery Mildew',
    pathogen: 'Erysiphe spp., Sphaerotheca spp.',
    severity: 'high',
    affectedPlants: ['cucumber', 'tomato', 'strawberry', 'pepper', 'basil'],
    visualSymptoms: {
      roots: 'Kökler genellikle etkilenmez.',
      leaves: 'Yaprak yüzeyinde beyaz pudra görünümlü lekeler. Zamanla tüm yaprak yüzeyini kaplar.',
      stem: 'Genç sürgünlerde beyaz toz benzeri kaplama.',
    },
    causes: [
      'Yetersiz hava sirkülasyonu',
      'Yüksek nem (>85%)',
      'Bitki yapraklarına su değmesi',
      'Fazla azot gübrelemesi',
      'Aşırı sık dikim',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Acil Tedavi',
        steps: [
          'Etkilenen yaprakları hemen koparın ve imha edin',
          'Bikarbonat soda çözeltisi hazırlayın (10g/L su)',
          'Yapraklara sprey yapın (sadece yapraklar, su sistemi değil)',
          'Potasyum bikarbonat spreyi uygulayın',
          'Neem yağı solüsyonu (5mL/L) uygulayın',
        ],
      },
      {
        type: 'systemic',
        title: 'Ortam Düzenlemesi',
        steps: [
          'Nem oranını %65\'in altına düşürün',
          'Fanları artırın, hava sirkülasyonunu güçlendirin',
          'Bitki aralarını açın (seyreltme)',
          'Yapraklara su değmesini önleyin',
          'Azot gübreyi geçici olarak azaltın',
        ],
      },
    ],
    prevention: ['Nem %70 altında tutun', 'İyi hava sirkülasyonu sağlayın', 'Yaprakları ıslatmayın'],
    recoveryChance: 80,
    recoveryTime: '1-2 hafta',
  },

  nutrient_deficiency_nitrogen: {
    id: 'nutrient_deficiency_nitrogen',
    name: 'Azot Eksikliği',
    nameEn: 'Nitrogen Deficiency',
    pathogen: 'Beslenme Bozukluğu',
    severity: 'medium',
    affectedPlants: ['lettuce', 'basil', 'tomato', 'cucumber', 'spinach', 'pepper'],
    visualSymptoms: {
      roots: 'Kökler ince ve soluk görünür.',
      leaves: 'Alt yapraklardan başlayan açık sarı renk değişimi. Damarlarda yeşil kalma.',
      stem: 'Soluk yeşil veya sarımsı gövde.',
    },
    causes: [
      'Düşük besin konsantrasyonu (EC çok düşük)',
      'pH çok yüksek veya çok düşük',
      'Besin solüsyonunun bitmesi',
      'Yanlış gübre karışımı',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Hızlı Çözüm',
        steps: [
          'EC değerini ölçün (hedef: bitkiye göre 1.0-3.0 mS/cm)',
          'pH\'ı kontrol edin ve 5.5-6.5 aralığına ayarlayın',
          'Azot bazlı gübre ekleyin (kalsiyum nitrat Ca(NO₃)₂)',
          'Besin solüsyonunu 2-3 gün içinde kontrol edin',
          'Haftalık EC takibini düzenli yapın',
        ],
      },
    ],
    prevention: ['Haftada en az 2 kez EC ölçün', 'pH\'ı günlük kontrol edin', 'Kaliteli gübre kullanın'],
    recoveryChance: 95,
    recoveryTime: '5-10 gün',
  },

  calcium_deficiency: {
    id: 'calcium_deficiency',
    name: 'Kalsiyum Eksikliği',
    nameEn: 'Calcium Deficiency',
    pathogen: 'Beslenme Bozukluğu',
    severity: 'high',
    affectedPlants: ['tomato', 'pepper', 'cucumber', 'lettuce'],
    visualSymptoms: {
      roots: 'Kök uçlarında kahverengi renk değişimi.',
      leaves: 'Genç yapraklarda kıvrılma ve kenar yanıklığı. Yaprak uçlarında kahverengi nekroz.',
      stem: 'Domates ve biberde çiçek ucu çürüklüğü (BER - Blossom End Rot).',
    },
    causes: [
      'Besin solüsyonunda Ca eksikliği',
      'Yüksek pH (>7.0) - kalsiyum çözünmez',
      'Aşırı potasyum veya magnezyum (antagonizm)',
      'Düşük transpirason (yetersiz hava akışı)',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Tedavi',
        steps: [
          'Kalsiyum nitrat (CaNO₃) solüsyonuna ekleyin',
          'pH\'ı 6.0-6.5 aralığına ayarlayın',
          'Hava sirkülasyonunu artırın',
          'Yapraklara kalsiyum spreyi uygulayın (%0.5 CaCl₂)',
          'K ve Mg gübre miktarlarını geçici olarak azaltın',
        ],
      },
    ],
    prevention: ['Ca:Mg:K dengesini koruyun', 'pH\'ı düzenli takip edin', 'Hava sirkülasyonu sağlayın'],
    recoveryChance: 75,
    recoveryTime: '1-2 hafta',
  },

  iron_deficiency: {
    id: 'iron_deficiency',
    name: 'Demir Eksikliği',
    nameEn: 'Iron Deficiency (Chlorosis)',
    pathogen: 'Beslenme Bozukluğu',
    severity: 'medium',
    affectedPlants: ['spinach', 'tomato', 'pepper', 'cucumber', 'basil'],
    visualSymptoms: {
      roots: 'Genellikle kökler normal görünür.',
      leaves: 'Genç yapraklarda damarlar arası sararma (interveinal chlorosis). Damarlar yeşil kalır.',
      stem: 'Yeni sürgünler soluk sarı-yeşil renkte.',
    },
    causes: [
      'pH >7.0 (demir çözünmez hale gelir)',
      'Aşırı fosfat (demir bağlanması)',
      'Alkalin besin solüsyonu',
      'Yetersiz demir şelat konsantrasyonu',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Tedavi',
        steps: [
          'pH\'ı 5.5-6.0 aralığına düşürün (kritik!)',
          'Fe-EDTA veya Fe-DTPA şelat ekleyin (1-2 ppm Fe)',
          'Fosfat miktarını geçici olarak azaltın',
          'Yapraklara demir sülfat spreyi (FeSO₄ %0.1) uygulayın',
        ],
      },
    ],
    prevention: ['pH\'ı 5.5-6.5 arasında tutun', 'Şelatlı demir kullanın', 'Fosfat dozunu aşmayın'],
    recoveryChance: 90,
    recoveryTime: '1-2 hafta',
  },

  botrytis: {
    id: 'botrytis',
    name: 'Gri Küf (Botrytis)',
    nameEn: 'Grey Mold (Botrytis)',
    pathogen: 'Botrytis cinerea',
    severity: 'high',
    affectedPlants: ['strawberry', 'lettuce', 'tomato', 'basil'],
    visualSymptoms: {
      roots: 'Kök boğazında gri-kahverengi çürüme.',
      leaves: 'Gri-kahverengi lekeler, zamanla gri tüylü (misel) kaplama oluşur.',
      stem: 'Gövdede gri küflü çürüme lekeleri.',
    },
    causes: [
      'Yüksek nem (>85%)',
      'Düşük sıcaklık ve yüksek nem kombinasyonu',
      'Hava sirkülasyonu yetersizliği',
      'Bitki döküntülerinin birikmesi',
      'Mekanik yaralanmalar',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Acil Müdahale',
        steps: [
          'Tüm etkilenen bitki parçalarını steril makasla kesin',
          'Bitki atıklarını hemen uzaklaştırın ve imha edin',
          'Biyofungisit uygulayın (Bacillus subtilis bazlı)',
          'Hava sirkülasyonunu maksimuma çıkarın',
          'Potasyum bikarbonat spreyi uygulayın',
        ],
      },
      {
        type: 'prevention',
        title: 'Önleyici Tedbirler',
        steps: [
          'Nem oranını %70 altında tutun',
          'Düzenli hava sirkülasyonu sağlayın',
          'Ölü yaprak ve bitki artıklarını temizleyin',
          'Bitkileri çok sık dikmeyin',
        ],
      },
    ],
    prevention: ['Nem kontrolü yapın', 'Hava sirkülasyonu sağlayın', 'Bitki atıklarını temizleyin'],
    recoveryChance: 65,
    recoveryTime: '2-3 hafta',
  },

  aphids: {
    id: 'aphids',
    name: 'Yaprak Biti (Afid)',
    nameEn: 'Aphids',
    pathogen: 'Aphididae',
    severity: 'high',
    affectedPlants: ['lettuce', 'basil', 'tomato', 'pepper', 'spinach'],
    visualSymptoms: {
      roots: 'Kökler genellikle etkilenmez.',
      leaves: 'Yaprak altlarında küçük yeşil, siyah veya sarı böcekler. Yaprak kıvrılması ve sararma.',
      stem: 'Genç sürgünlerde yoğun koloni. Yapışkan madde (bal özü) salgısı.',
    },
    causes: [
      'Dışarıdan bulaşma (enfekte bitki materyali)',
      'Yetersiz kontrol önlemleri',
      'Yüksek azotlu büyüme (tatlı, yumuşak dokular)',
      'Doğal düşman yokluğu',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Acil Müdahale',
        steps: [
          'Etkilenen bitkiyi izole edin',
          'Güçlü su spreyi ile böcekleri uzaklaştırın',
          'Sarı yapışkan tuzaklar yerleştirin',
          'Insektisidal sabun solüsyonu hazırlayın (5mL/L)',
          'Neem yağı karışımı uygulayın',
        ],
      },
      {
        type: 'biological',
        title: 'Biyolojik Kontrol',
        steps: [
          'Uğur böceği (Coccinella) bırakın',
          'Parazitoid arı (Aphidius) kullanın',
          'Sarı yapışkan tuzak sıklığını artırın',
        ],
      },
    ],
    prevention: ['Karantina prosedürü uygulayın', 'Düzenli kontrol yapın', 'Sarı tuzak kullanın'],
    recoveryChance: 85,
    recoveryTime: '1-2 hafta',
  },

  whitefly: {
    id: 'whitefly',
    name: 'Beyaz Sinek',
    nameEn: 'Whitefly',
    pathogen: 'Trialeurodes vaporariorum',
    severity: 'high',
    affectedPlants: ['cucumber', 'tomato', 'pepper', 'basil'],
    visualSymptoms: {
      roots: 'Kökler etkilenmez.',
      leaves: 'Yaprak altında küçük beyaz böcekler. Bitkiye dokunulduğunda bulut gibi uçarlar.',
      stem: 'Yapışkan bal özü birikimi, ardından siyah fumajin fungus.',
    },
    causes: [
      'Kontamine fide veya bitki materyali',
      'Açık pencere/kapılardan giriş',
      'Yüksek sıcaklık (>28°C)',
    ],
    treatments: [
      {
        type: 'immediate',
        title: 'Acil Müdahale',
        steps: [
          'Sarı yapışkan tuzakları asın',
          'Insektisidal sabun spreyi uygulayın',
          'Neem yağı/limon karışımı hazırlayın',
          'Spinosad bazlı biyopestisit kullanın',
          'Alt yaprakları temizleyin',
        ],
      },
    ],
    prevention: ['Girişlerde ağ filtre kullanın', 'Sarı tuzak asın', 'Yeni bitkileri karantinaya alın'],
    recoveryChance: 80,
    recoveryTime: '2-3 hafta',
  },
};

export const GROWTH_STAGES = {
  seedling: { id: 'seedling', name: 'Fide', icon: '🌱', days: '0-7' },
  vegetative: { id: 'vegetative', name: 'Vejetatif', icon: '🌿', days: '7-30' },
  flowering: { id: 'flowering', name: 'Çiçeklenme', icon: '🌸', days: '30-50' },
  fruiting: { id: 'fruiting', name: 'Meyve', icon: '🍅', days: '50-80' },
  harvest: { id: 'harvest', name: 'Hasat', icon: '🌾', days: '80+' },
};

export const SYMPTOM_KEYWORDS = {
  sarı: ['nutrient_deficiency_nitrogen', 'iron_deficiency', 'calcium_deficiency'],
  sararma: ['nutrient_deficiency_nitrogen', 'iron_deficiency'],
  beyaz: ['powdery_mildew'],
  pudra: ['powdery_mildew'],
  küf: ['powdery_mildew', 'botrytis'],
  gri: ['botrytis'],
  çürüme: ['root_rot', 'botrytis'],
  kök: ['root_rot'],
  böcek: ['aphids', 'whitefly'],
  yaprak: ['aphids', 'whitefly', 'powdery_mildew'],
  solma: ['root_rot', 'nutrient_deficiency_nitrogen'],
  nekroz: ['calcium_deficiency', 'botrytis'],
  leke: ['botrytis', 'powdery_mildew'],
};
